const itemList = [
  {
    ID: 0,
    Name: "Torch",
    Price: 200,
    srcImage: require("../images/items/torch.png"),
    Quantity: 0,
  },
  {
    ID: 1,
    Name: "Arrow",
    Price: 40,
    srcImage: require("../images/items/arrow.png"),
    Quantity: 0,
  },
  {
    ID: 2,
    Name: "Dagger",
    Price: 200,
    srcImage: require("../images/items/dagger.webp"),
    Quantity: 0,
  },
  {
    ID: 3,
    Name: "Chain Armor",
    Price: 1000,
    srcImage: require("../images/items/chain_armor.png"),
    Quantity: 0,
  },
  {
    ID: 4,
    Name: "Chain Coif",
    Price: 500,
    srcImage: require("../images/items/chain_coif.png"),
    Quantity: 0,
  },
  {
    ID: 5,
    Name: "Chain Gauntlets",
    Price: 400,
    srcImage: require("../images/items/chain_gauntlets.png"),
    Quantity: 0,
  },
  {
    ID: 6,
    Name: "Dappled White Cured Meat",
    Price: 100,
    srcImage: require("../images/items/dappled_white_cured_meat.png"),
    Quantity: 0,
  },
  {
    ID: 7,
    Name: "Immunizing White Cured Meat",
    Price: 100,
    srcImage: require("../images/items/immunizing_white_cured_meat.png"),
    Quantity: 0,
  },
  {
    ID: 8,
    Name: "Invigorating White Cured Meat",
    Price: 100,
    srcImage: require("../images/items/invigorating_white_cured_meat.png"),
    Quantity: 0,
  },
  {
    ID: 9,
    Name: "Shield",
    Price: 700,
    srcImage: require("../images/items/shield.png"),
    Quantity: 0,
  },
  {
    ID: 10,
    Name: "Pot",
    Price: 50,
    srcImage: require("../images/items/pot.png"),
    Quantity: 0,
  },
  {
    ID: 11,
    Name: "Fire Pot",
    Price: 200,
    srcImage: require("../images/items/fire_pot.png"),
    Quantity: 0,
  },
  {
    ID: 12,
    Name: "Lightning Pot",
    Price: 200,
    srcImage: require("../images/items/lightning_pot.png"),
    Quantity: 0,
  },
  {
    ID: 13,
    Name: "Swarm Pot",
    Price: 200,
    srcImage: require("../images/items/swarm_pot.png"),
    Quantity: 0,
  },
  {
    ID: 14,
    Name: "Smithing Stone",
    Price: 250,
    srcImage: require("../images/items/smithing_stone.png"),
    Quantity: 0,
  },
  {
    ID: 15,
    Name: "Stonesword Key",
    Price: 2000,
    srcImage: require("../images/items/stonesword_key.png"),
    Quantity: 0,
  },
  {
    ID: 16,
    Name: "Rune Arc",
    Price: 2000,
    srcImage: require("../images/items/rune_arc.png"),
    Quantity: 0,
  },
  {
    ID: 17,
    Name: "Rainbow Stone",
    Price: 10,
    srcImage: require("../images/items/rainbow_stone.png"),
    Quantity: 0,
  },
  {
    ID: 18,
    Name: "Glowstone",
    Price: 25,
    srcImage: require("../images/items/glowstone.png"),
    Quantity: 0,
  },
  {
    ID: 19,
    Name: "Magic Grease",
    Price: 350,
    srcImage: require("../images/items/magic_grease.png"),
    Quantity: 0,
  },
  {
    ID: 20,
    Name: "Fire Grease",
    Price: 350,
    srcImage: require("../images/items/fire_grease.png"),
    Quantity: 0,
  },
  {
    ID: 21,
    Name: "Lightning Grease",
    Price: 350,
    srcImage: require("../images/items/lightning_grease.png"),
    Quantity: 0,
  },
  {
    ID: 22,
    Name: "Neutralizing Boluses",
    Price: 100,
    srcImage: require("../images/items/neutralizing_boluses.png"),
    Quantity: 0,
  },
  {
    ID: 23,
    Name: "Preserving Boluses",
    Price: 100,
    srcImage: require("../images/items/preserving_boluses.png"),
    Quantity: 0,
  },
  {
    ID: 24,
    Name: "Stanching Boluses",
    Price: 100,
    srcImage: require("../images/items/stanching_boluses.png"),
    Quantity: 0,
  },
  {
    ID: 25,
    Name: "Kukri",
    Price: 25,
    srcImage: require("../images/items/kukri.png"),
    Quantity: 0,
  },
  {
    ID: 26,
    Name: "Glintstone Scrap",
    Price: 10,
    srcImage: require("../images/items/glintstone_scrap.png"),
    Quantity: 0,
  },
  {
    ID: 27,
    Name: "Heavy Meteorite Fragment",
    Price: 150,
    srcImage: require("../images/items/heavy_meteorite_fragment.png"),
    Quantity: 0,
  },
  {
    ID: 28,
    Name: "Poisoned Stone",
    Price: 20,
    srcImage: require("../images/items/poisoned_stone.png"),
    Quantity: 0,
  },
  {
    ID: 29,
    Name: "Gold Pickled Fowl Foot",
    Price: 1000,
    srcImage: require("../images/items/gold-pickled_fowl_foot.png"),
    Quantity: 0,
  },
  {
    ID: 30,
    Name: "Silver Pickled Fowl Foot",
    Price: 40,
    srcImage: require("../images/items/silver_pickled_fowl_foot.png"),
    Quantity: 0,
  },
  {
    ID: 31,
    Name: "Bolt",
    Price: 20,
    srcImage: require("../images/items/bolt.png"),
    Quantity: 0,
  },
];

export default itemList;
